src/tanabe_shinnosuke/beans/Message.java
package tanabe_shinnosuke.beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private String text;
	private Date insert_date;
	private Date update_date;
	private int user_id;
	private int post_id;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getInsertDate() {
		return insert_date;
	}

	public void setInsertDate(Date insert_date) {
		this.insert_date = insert_date;
	}

	public Date getUpdateDate() {
		return update_date;
	}

	public void setUpdateDate(Date update_date) {
		this.update_date = update_date;
	}

	public int getUserId() {
		return user_id;
	}

	public void setUserId(int user_id) {
		this.user_id = user_id;
	}

	public int getPostId() {
		return post_id;
	}

	public void setPostId(int post_id) {
		this.post_id = post_id;
	}

}

src/tanabe_shinnosuke/beans/Post.java
package tanabe_shinnosuke.beans;

import java.io.Serializable;
import java.util.Date;

public class Post implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private String title;
	private String main;
	private String category;
	private Date insert_date;
	private Date update_date;
	private int user_id;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMain() {
		return main;
	}

	public void setMain(String main) {
		this.main = main;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Date getInsertDate() {
		return insert_date;
	}

	public void setInsertDate(Date insert_date) {
		this.insert_date = insert_date;
	}

	public Date getUpdateDate() {
		return update_date;
	}

	public void setUpdateDate(Date update_date) {
		this.update_date = update_date;
	}

	public int getUserId() {
		return user_id;
	}

	public void setUserId(int user_id) {
		this.user_id = user_id;
	}

}

src/tanabe_shinnosuke/beans/User.java
package tanabe_shinnosuke.beans;


import java.io.Serializable;

public class User implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private String login_id;
	private String password;
	private String name;
	private int branch_id;
	private int position_id;
	private int is_deleted;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLoginId() {
		return login_id;
	}

	public void setLoginId(String login_id) {
		this.login_id = login_id;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getBranchId() {
		return branch_id;
	}

	public void setBranchId(int branch_id) {
		this.branch_id = branch_id;
	}

	public int getPositionId() {
		return position_id;
	}

	public void setPositionId(int position_id) {
		this.position_id = position_id;
	}

	public int getIsDeleted() {
		return is_deleted;
	}

	public void setIsDeleted(int is_deleted) {
		this.is_deleted = is_deleted;
	}


}

src/tanabe_shinnosuke/controller/HomeServlet.java
package tanabe_shinnosuke.controller;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import tanabe_shinnosuke.beans.Message;
import tanabe_shinnosuke.beans.Post;
import tanabe_shinnosuke.beans.User;
import tanabe_shinnosuke.service.MessageService;
import tanabe_shinnosuke.service.PostService;
import tanabe_shinnosuke.service.UserService;


@WebServlet(urlPatterns = { "/index.jsp"})

public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;


	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException,
	ServletException {

		Date now = new Date();
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
		String begin = "2017/11/01";
		String time = sdf.format(now);


		//絞込み
		String start = request.getParameter("start");
		String end = request.getParameter("end");

		String category = request.getParameter("category");

		if(StringUtils.isBlank(start) == true && StringUtils.isBlank(end) == true) { //指定なし
			List<Post> posts = new PostService().getPost(begin, time, category);
			request.setAttribute("posts", posts);
		}

		if(StringUtils.isBlank(start) == true && StringUtils.isBlank(end) == false) { //終わりのみ
			List<Post> posts = new PostService().getPost(begin, end, category);
			request.setAttribute("posts", posts);
		}

		if(StringUtils.isBlank(start) == false && StringUtils.isBlank(end) == true) { //開始のみ
			List<Post> posts = new PostService().getPost(start, time, category);
			request.setAttribute("posts", posts);
		}

		if(StringUtils.isBlank(start) == false && StringUtils.isBlank(end) == false) { //両方あり
			List<Post> posts = new PostService().getPost(start, end, category);
			request.setAttribute("posts", posts);
		}

		List<User> userInfo = new UserService().getUserInfo();

		List<Message> messages = new MessageService().getMessage();

		request.setAttribute("userInfo", userInfo);
		request.setAttribute("comments", messages);
		request.setAttribute("Start", start);
		request.setAttribute("End", end);
		request.setAttribute("Category", category);
		request.getRequestDispatcher("/home.jsp").forward(request, response);
	}
}

src/tanabe_shinnosuke/controller/LoginServlet.java
package tanabe_shinnosuke.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import tanabe_shinnosuke.beans.User;
import tanabe_shinnosuke.service.LoginService;

@WebServlet(urlPatterns = {"/login"})
public class LoginServlet extends HttpServlet {
	private static final long serivalVersionUID =1L;

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException,
	ServletException {
		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException,
	ServletException {

		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");

		LoginService loginService = new LoginService();
		User user = loginService.login(login_id, password);
		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		if(user != null && user.getIsDeleted() == 1) {
			session.setAttribute("loginUser", user);
			response.sendRedirect("./");
		} else if(user != null && user.getIsDeleted() == 0) {

			messages.add("アカウント停止中です");
			request.setAttribute("LoginId", request.getParameter("login_id")); //値保持

			request.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("login.jsp").forward(request, response);

		} else {

			messages.add("ログインに失敗しました");

			request.setAttribute("LoginId", request.getParameter("login_id")); //値保持

			request.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("login.jsp").forward(request, response);
		}

	}
}

src/tanabe_shinnosuke/controller/ManageServlet.java
package tanabe_shinnosuke.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import tanabe_shinnosuke.beans.Branch;
import tanabe_shinnosuke.beans.Position;
import tanabe_shinnosuke.beans.User;
import tanabe_shinnosuke.service.BranchService;
import tanabe_shinnosuke.service.PositionService;
import tanabe_shinnosuke.service.UserService;




@WebServlet(urlPatterns = { "/manage" })
public class ManageServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		List<User> userInfo = new UserService().getUserInfo();
		List<Branch> branch = new BranchService().getBranch();
		List<Position> position = new PositionService().getPosition();

		request.setAttribute("userInfo", userInfo);
		request.setAttribute("branch", branch);
		request.setAttribute("position", position);

		request.getRequestDispatcher("/manage.jsp").forward(request, response);

	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		User user = getUser(request);

		new UserService().stop(user);
		request.setAttribute("User", user);
		response.sendRedirect("manage");
	}

	private User getUser(HttpServletRequest request)
			throws IOException, ServletException {

		User user = new User();

		user.setId(Integer.parseInt(request.getParameter("id")));

		if(Integer.parseInt(request.getParameter("is_deleted")) == 1) {
			user.setIsDeleted(Integer.parseInt("0"));
		}

		if(Integer.parseInt(request.getParameter("is_deleted")) == 0) {
			user.setIsDeleted(Integer.parseInt("1"));
		}

		return user;
	}

}

src/tanabe_shinnosuke/controller/NewPostServlet.java
package tanabe_shinnosuke.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import tanabe_shinnosuke.beans.Post;
import tanabe_shinnosuke.beans.User;
import tanabe_shinnosuke.service.PostService;

@WebServlet(urlPatterns = { "/newpost" })
public class NewPostServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException,
	ServletException {
		request.getRequestDispatcher("newpost.jsp").forward(request, response);
	}


	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();

		List<String> messages = new ArrayList<String>();

		if (isValid(request, messages) == true) {

			User user = (User) session.getAttribute("loginUser");

			Post post = new Post();
			post.setTitle(request.getParameter("title"));
			post.setMain(request.getParameter("main"));
			post.setCategory(request.getParameter("category"));
			post.setUserId(user.getId());

			new PostService().register(post);

			response.sendRedirect("./");
		} else {

			Post post = new Post();
			post.setTitle(request.getParameter("title"));
			post.setMain(request.getParameter("main"));
			post.setCategory(request.getParameter("category"));

			request.setAttribute("Posts", post);
			request.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("newpost.jsp").forward(request, response);
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) { //バリデーション

		String title = request.getParameter("title");
		String main = request.getParameter("main");
		String category = request.getParameter("category");

		if(StringUtils.isBlank(title) == true) {
			messages.add("件名を入力してください");
		}
		if(StringUtils.isBlank(title) == false && 30 < title.length()) {
			messages.add("件名は30文字以下で入力してください");
		}

		if(StringUtils.isBlank(main) == true) {
			messages.add("本文を入力してください");
		}

		if(StringUtils.isBlank(main) == false && 1000 < main.length()) {
			messages.add("本文は1,000字以内で入力してください");
		}

		if(StringUtils.isBlank(category) == true) {
			messages.add("カテゴリーを入力してください");
		}

		if(StringUtils.isBlank(category) == false && 10 < category.length()) {
			messages.add("カテゴリーは10字以内で入力してください");
		}

		if(messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}

src/tanabe_shinnosuke/controller/SignUpServlet.java
package tanabe_shinnosuke.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import tanabe_shinnosuke.beans.Branch;
import tanabe_shinnosuke.beans.Position;
import tanabe_shinnosuke.beans.User;
import tanabe_shinnosuke.service.BranchService;
import tanabe_shinnosuke.service.PositionService;
import tanabe_shinnosuke.service.UserService;

@WebServlet(urlPatterns = {"/signup"})
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException,
	ServletException {

		List<Branch> branch = new BranchService().getBranch();
		List<Position> position = new PositionService().getPosition();

		request.setAttribute("Branch", branch);
		request.setAttribute("Position", position);

		request.getRequestDispatcher("signup.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException,
		ServletException {

		List<String> message = new ArrayList<String>();

		List<Branch> branch = new BranchService().getBranch();
		List<Position> position = new PositionService().getPosition();

		if(isValid(request, message) == true) {
			User user = new User();
			user.setLoginId(request.getParameter("login_id"));
			user.setPassword(request.getParameter("password"));
			user.setName(request.getParameter("name"));
			user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));
			user.setPositionId(Integer.parseInt(request.getParameter("position_id")));
			user.setIsDeleted(Integer.parseInt("1"));

			new UserService().register(user);

			response.sendRedirect("manage");
		} else {

			User user = new User();
			user.setLoginId(request.getParameter("login_id"));
			user.setPassword(request.getParameter("password"));
			user.setName(request.getParameter("name"));
			user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));
			user.setPositionId(Integer.parseInt(request.getParameter("position_id")));

			request.setAttribute("SignUpUser", user);

			request.setAttribute("Branch", branch);
			request.setAttribute("Position", position);

			request.setAttribute("errorMessages", message);
			request.getRequestDispatcher("signup.jsp").forward(request, response);
		}

	}

		private boolean isValid(HttpServletRequest request, List<String> messages) {
			String loginId = request.getParameter("login_id");
			String password = request.getParameter("password");
			String passwordConfirm = request.getParameter("passwordConfirm");
			String name = request.getParameter("name");
			String branchId = request.getParameter("branch_id");
			String positionId = request.getParameter("position_id");

			User LoginId = new UserService().LoginId(loginId);


			if(LoginId != null) {
				messages.add("入力されたログインIDはすでに使用されています");
			}

			if(StringUtils.isBlank(loginId) == true) {
				messages.add("ログインIDを入力してください");
			}

			if(StringUtils.isBlank(loginId) == false && (20 < loginId.length() || 6 > loginId.length())) {
				messages.add("ログインIDは6文字以上、20文字以内で入力してください");
			}

			if(StringUtils.isBlank(loginId) == false && loginId.matches("\\W*")) {
				messages.add("ログインIDは半角英数字で入力してください");
			}

			if(StringUtils.isBlank(password) == true) {
				messages.add("パスワードを入力してください");
			}

			if(StringUtils.isBlank(password) == false && (20 < password.length() || 6 > password.length())) {
				messages.add("パスワードは6文字以上、20文字以内で入力してください");
			}

			if(password.equals(passwordConfirm)) {

			} else {
				messages.add("入力されたパスワードと確認用パスワードが一致しません");
			}

			if(StringUtils.isBlank(name) == true) {
				messages.add("名称を入力してください");
			}

			if(StringUtils.isBlank(name) == false && 10 < name.length()) {
				messages.add("名称は10文字以内で入力してください");
			}

			if(branchId.matches("0")) {
				messages.add("支店を選択してください");
			}

			if(positionId.matches("0")) {
				messages.add("部署・役職を選択してください");
			}

			if((positionId.equals("1") || positionId.equals("2")) && branchId.equals("1") == false) {
				messages.add("支店と部署・役職が不正な組み合わせです");
			}

			if(branchId.equals("1") && (positionId.equals("3") || positionId.equals("4")) == true) {
				messages.add("支店と部署・役職が不正な組み合わせです");
			}

			if(messages.size() == 0) {
				return true;
			} else {
				return false;
			}
		}

	}

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored= "false" %>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix= "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri= "http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ホーム画面</title>
	<link rel="stylesheet" href="./css/style.css">

	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="./js/ajax.js"></script>

</head>
<body>

<h1>ホーム画面</h1>


<c:if test="${ not empty loginUser }">

<div class="header">
	<c:if test="${ not empty loginUser }">
	<c:if test="${loginUser.branchId == 1 && loginUser.positionId == 1 }">
		<a href="manage">ユーザー管理画面</a>
	</c:if>
		<a href="newpost">新規投稿画面</a>
		<a href="logout" style="float: right;">ログアウト</a>
	</c:if>
</div>
<hr>

<c:if test="${ not empty errorMessages }">
	<div class="errorMessages">
		<ul>
			<c:forEach items="${errorMessages}" var="message">
				<li><c:out value="${message}" />
			</c:forEach>
		</ul>
	</div>
	<c:remove var="errorMessages" scope="session"/>
</c:if>

<h3>絞込み</h3>

<form action="./" method="get">
	<span>期間を指定</span>
	<input type="date" value="${Start}" name="start" >～
	<input type="date" value="${End}" name="end" ><br/><br/>
	<label for="category">カテゴリー検索</label>
	<input name="category" value="${Category}" id="category"><br/><br/>

	<input type="submit" value="絞込み実行"><br />
</form>
<br />
<a href="./">検索条件リセット</a>
<hr style="margin_buttom: 30px;">

    <c:forEach items="${posts}" var="post">
    <section class='message-area'>
    <section class='view-area'>
    	<p>投稿</p><br/>
    	<label for="title">件名</label><br />
		<span class="title"><c:out value="${post.title}" /></span><br /><br />

		<label for="main">本文</label><br />
		<c:forEach var="spost" items="${fn:split(post.main, '
			')}">
    		<div class="post-split"><c:out value="${spost}" /></div><br />
		</c:forEach>

		<label for="category">カテゴリー</label><br />
		<div class="category"><c:out value="${post.category}" /></div><br />

		<label for="date">投稿日時</label><br />
		<div class="date"><fmt:formatDate value="${post.insertDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div><br />

		<label for="post_name">投稿者</label><br />
		<c:forEach items="${userInfo}" var="userInfo">
			<c:if test="${ userInfo.id == post.userId }">
				<div class="post_name"><c:out value="${userInfo.name}" /></div><br />
			</c:if>
		</c:forEach>
		<c:if test="${loginUser.id == post.userId }">
			<form action="postdelete" method="post">
				<input type="hidden" name="id" value="${post.id}">
				<button type="submit" onclick='return confirm("本当に削除しますか？");' >投稿削除</button><br />
			</form>
		</c:if>
    </section>

    <section class='comment-area'>
      <section class='view-area'>
      	<c:forEach items="${comments}" var="comment">
		<c:if test="${post.id == comment.postId }">
		<hr style="margin_buttom: 30px;">
		<p>コメント</p><br/>

			<input type="hidden" name="message_id" value="${comment.id}">

			<label for="text">本文</label><br />

			<c:forEach var="scomment" items="${fn:split(comment.text, '
				')}">
    			<div><c:out value="${scomment}" /></div><br />
			</c:forEach>

			<label for="date"> 投稿日時 </label><br />
			<div class="date"><fmt:formatDate value="${comment.insertDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div><br />


			<label for="comment_name">投稿者</label><br />
			<c:forEach items="${userInfo}" var="userInfo">
				<c:if test="${ userInfo.id == comment.userId }">
					<div class="comment_name"><c:out value="${userInfo.name}" /></div><br />
				</c:if>
			</c:forEach>
			<c:if test="${loginUser.id == comment.userId }">
				<form action="messagedelete" method="post">
					<input type="hidden" name="message_id" id="message_id" value="${comment.id}">
					<button type="submit" onclick='return confirm("本当に削除しますか？");' >コメント削除</button><br />
				</form>
			</c:if>
			</c:if>
			</c:forEach>
      </section>

      <section class='error-area'>
      	<ul></ul>
      </section>

      <section class='form-area'>
        <form id='register-form'>
        	<c:forEach items="${userInfo}" var="userInfo">
				<c:if test="${ userInfo.id == loginUser.id }">
					<input type="hidden" id="comment_name" value="${userInfo.name}">
				</c:if>
			</c:forEach>
        	<input type='hidden' id='message_id' value="${post.id }">
        	<input type='hidden' id='user_id' value="${loginUser.id }">

        	<%
			java.util.Date now = new java.util.Date();
			java.text.SimpleDateFormat a = new java.text.SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
			String time = a.format(now);
			%>

			<input type="hidden" id="time" value="<%= time %>">

        	<div>
        	<label id="name-label" for="text">本文</label>
        	<textarea name="text" rows="5" cols="20" id='text' class='comment-text-area'
        	style="margin: 0px 0px 0px 0px; width: 589px; height: 198px; font-size:15px;"></textarea>
        	<span>(500文字以下)</span>
        	</div>
        	<div>
        		<button type='button' id='register'>コメント投稿</button>
        	</div>
        </form>
      </section>

    </section>
    </section>
    </c:forEach>


</c:if>


<div class="copyright">Copyright(c)Shinnosuke Tanabe
</div>
</body>
</html>

WebContent/manage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored= "false" %>
<%@taglib prefix= "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri= "http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

	<link rel="stylesheet" href="./css/style.css">

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>ユーザー管理画面</title>

</head>
<body>
<h1>ユーザー管理画面</h1>

<div class="header">
	<c:if test="${ not empty loginUser }">
		<a href="signup">ユーザー新規登録画面</a>
		<a href="./">ホーム画面</a>
		<a href="logout" style="float: right;">ログアウト</a>
	</c:if>
</div>
<hr>

<c:if test="${ not empty errorMessages }">
	<div class="errorMessages">
		<ul>
			<c:forEach items="${errorMessages}" var="message">
				<li><c:out value="${message}" />
			</c:forEach>
		</ul>
	</div>
	<c:remove var="errorMessages" scope="session"/>
</c:if>

<div id="userInfo">
	<c:forEach items="${userInfo}" var="userInfo">
	<ul>

		<li  id="login-id">ログインID</li>
		<li class="login_id"><c:out value="${userInfo.loginId}" /></li>

		<li id="name">名称</li>
		<li class="name"><c:out value="${userInfo.name}" /></li>

		<li id="branch">支店</li>
				<c:forEach items="${branch}" var="branch">
			<c:if test="${ branch.id == userInfo.branchId }">
				<li class="branch_name"><c:out value="${branch.name}" /></li>
			</c:if>
		</c:forEach>

		<li id="position">部署・役職</li>
		<c:forEach items="${position}" var="position">
			<c:if test="${ position.id == userInfo.positionId }">
				<li class="position_name"><c:out value="${position.name}" /></li>
			</c:if>
		</c:forEach>
		</ul>


	<form action="manage" method="post" style="display: inline" id="account">
			<input type="hidden" name="id" value="${userInfo.id}">
			<input type="hidden" name="is_deleted" value="${userInfo.isDeleted}">
			<c:if test="${userInfo.isDeleted == 0}">
			<label for="is_deleted" id="account-stop">アカウント停止中</label>
			<c:if test="${loginUser.id != userInfo.id}">
				<button type="submit" onclick='return confirm("本当に復活しますか？");' >復活</button>
			</c:if>
			</c:if>
			<c:if test="${userInfo.isDeleted == 1}">
			<label for="is_deleted" id="account-move">アカウント稼動中</label>
			<c:if test="${loginUser.id != userInfo.id}">
				<button type="submit" onclick='return confirm("本当に停止しますか？");'>停止</button>
			</c:if>
			</c:if>
	</form>

		<a href="useredit?id=${userInfo.id}">ユーザー編集画面</a><br /><br />


		<hr>
	</c:forEach>
</div>

<div class="copyright">Copyright(c)Shinnosuke Tanabe
</div>
</body>
</html>